import Link from 'next/link';

export function Footer() {
  return (
    <footer className="border-t border-gray-200 bg-white py-8">
      <div className="mx-auto max-w-5xl px-6">
        <p className="text-center text-sm text-gray-500">
          Fineprint is a risk assessment and plain-language translation tool,
          not a law firm. No attorney-client relationship is created by using
          this service.
        </p>
      </div>
    </footer>
  );
}

export function AnalysisDisclaimer() {
  return (
    <p className="rounded-lg border border-gray-200 bg-surface px-5 py-4 text-sm text-gray-600">
      This analysis is generated by AI and is for informational purposes only.
      It does not constitute legal advice and should not be relied upon as such.
      Always consult a qualified lawyer for important legal matters.
    </p>
  );
}

export function Header({ showAuth = true }: { showAuth?: boolean }) {
  return (
    <header className="border-b border-gray-200 bg-white">
      <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
        <Link href="/" className="text-xl font-bold text-navy">
          Fineprint
        </Link>
        {showAuth && (
          <nav className="flex items-center gap-4">
            <Link
              href="/login"
              className="text-sm font-medium text-gray-600 hover:text-navy"
            >
              Log in
            </Link>
            <Link
              href="/login?mode=signup"
              className="rounded-lg bg-navy px-4 py-2 text-sm font-medium text-white hover:bg-navy/90"
            >
              Get started
            </Link>
          </nav>
        )}
      </div>
    </header>
  );
}

export function AppHeader() {
  return (
    <header className="border-b border-gray-200 bg-white">
      <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
        <Link href="/dashboard" className="text-xl font-bold text-navy">
          Fineprint
        </Link>
        <nav className="flex items-center gap-4">
          <Link
            href="/dashboard"
            className="text-sm font-medium text-gray-600 hover:text-navy"
          >
            Dashboard
          </Link>
          <Link
            href="/review"
            className="rounded-lg bg-navy px-4 py-2 text-sm font-medium text-white hover:bg-navy/90"
          >
            Review contract
          </Link>
        </nav>
      </div>
    </header>
  );
}
