import Link from 'next/link';
import Logo from '@/components/ui/Logo';
import AppNavSignOut from '@/components/AppNavSignOut';
import { ButtonPrimary, ButtonText } from '@/components/ui/Button';

export function Footer({ variant = 'app' }: { variant?: 'landing' | 'app' }) {
  if (variant === 'landing') {
    return (
      <footer className="border-t border-border bg-canvas">
        <div className="mx-auto max-w-5xl px-6 py-10 sm:px-10">
          <div className="mb-8 flex flex-col justify-between gap-6 sm:flex-row sm:items-start">
            <div>
              <Logo href="/" />
              <p className="mt-2 text-[15px] text-muted">
                Understand what you sign.
              </p>
            </div>
            <div className="flex gap-6 text-[15px] text-muted">
              <Link href="/privacy" className="hover:text-gray-900">
                Privacy
              </Link>
              <Link href="/terms" className="hover:text-gray-900">
                Terms
              </Link>
              <Link href="/contact" className="hover:text-gray-900">
                Contact
              </Link>
            </div>
          </div>
          <p className="text-[15px] text-muted">
            YourFineprint is a risk assessment tool, not a law firm. No
            attorney-client relationship is created by using this service.
          </p>
        </div>
      </footer>
    );
  }

  return (
    <footer className="border-t border-border bg-canvas py-10">
      <div className="mx-auto max-w-5xl px-6 sm:px-10">
        <p className="text-center text-[15px] leading-relaxed text-muted">
          YourFineprint is a risk assessment and plain-language translation tool,
          not a law firm. No attorney-client relationship is created by using
          this service.
        </p>
        <p className="mt-4 text-center text-[15px] text-muted">
          <Link href="/privacy" className="hover:text-gray-900">
            Privacy
          </Link>
          <span className="mx-3">·</span>
          <Link href="/terms" className="hover:text-gray-900">
            Terms
          </Link>
          <span className="mx-3">·</span>
          <Link href="/contact" className="hover:text-gray-900">
            Contact
          </Link>
        </p>
      </div>
    </footer>
  );
}

export function AnalysisDisclaimer() {
  return (
    <p className="card px-5 py-4 text-[15px] leading-relaxed text-muted">
      This analysis is generated by AI and is for informational purposes only.
      It does not constitute legal advice and should not be relied upon as such.
      Always consult a qualified lawyer for important legal matters.
    </p>
  );
}

export function Header() {
  return (
    <header className="nav-bar">
      <div className="flex w-full items-center justify-between px-6 sm:px-10 lg:px-12">
        <Logo href="/" size="nav" />
        <nav className="flex items-center gap-5 sm:gap-6">
          <ButtonText href="/login" className="text-[17px]">
            Log in
          </ButtonText>
          <ButtonPrimary href="/login" className="px-6 py-3 text-[16px]">
            Get started free
          </ButtonPrimary>
        </nav>
      </div>
    </header>
  );
}

export function AppHeader() {
  return (
    <header className="nav-bar">
      <div className="flex w-full items-center justify-between gap-4 px-6 sm:px-10 lg:px-12">
        <Logo href="/dashboard" size="nav" />
        <nav className="flex flex-wrap items-center justify-end gap-4 sm:gap-5">
          <Link
            href="/dashboard"
            className="text-[16px] font-medium text-muted hover:text-gray-900"
          >
            Dashboard
          </Link>
          <Link
            href="/review"
            className="text-[16px] font-medium text-muted hover:text-gray-900"
          >
            Review
          </Link>
          <Link
            href="/profile"
            className="text-[16px] font-medium text-muted hover:text-gray-900"
          >
            Profile
          </Link>
          <AppNavSignOut />
          <ButtonPrimary href="/review" className="px-5 py-2.5 text-[15px] sm:px-6 sm:py-3 sm:text-[16px]">
            Review contract
          </ButtonPrimary>
        </nav>
      </div>
    </header>
  );
}

export function PageHeader({
  title,
  subtitle,
}: {
  title: string;
  subtitle?: string;
}) {
  return (
    <div className="mb-10">
      <h1 className="text-[32px] font-semibold tracking-tight text-gray-900">
        {title}
      </h1>
      {subtitle && (
        <p className="mt-1.5 text-[16px] text-muted">{subtitle}</p>
      )}
    </div>
  );
}

