import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalDocument, LegalSection } from '@/components/LegalDocument';

export const metadata: Metadata = {
  title: 'Terms of Service — YourFineprint',
  description: 'Terms and conditions for using YourFineprint.',
};

export default function TermsPage() {
  return (
    <LegalDocument title="Terms of Service" lastUpdated="June 5, 2026">
      <LegalSection heading="Agreement">
        <p>
          By accessing or using YourFineprint, you agree to these Terms of Service. If
          you do not agree, do not use the service.
        </p>
      </LegalSection>

      <LegalSection heading="What YourFineprint is">
        <p>
          YourFineprint is an AI-powered tool that helps freelancers understand contract
          documents through plain-language summaries, risk indicators, and draft
          negotiation emails.
        </p>
        <p>
          <strong className="text-gray-900">YourFineprint is not a law firm and does not
          provide legal advice.</strong> Output from the service is for informational
          purposes only. No attorney-client relationship is created. For important
          legal decisions, consult a qualified lawyer licensed in your jurisdiction.
        </p>
      </LegalSection>

      <LegalSection heading="Eligibility">
        <p>
          You must be at least 18 years old and able to form a binding contract to
          use YourFineprint. You are responsible for ensuring you have the right to
          upload and analyze any document you submit.
        </p>
      </LegalSection>

      <LegalSection heading="Your account">
        <p>
          You are responsible for keeping your login credentials secure and for all
          activity under your account. Notify us promptly if you suspect unauthorized
          access.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5">
          <li>Upload malware, unlawful content, or documents you do not have rights to use</li>
          <li>Attempt to reverse engineer, scrape, or disrupt the service</li>
          <li>Use YourFineprint output as a substitute for professional legal counsel</li>
          <li>Share account access or resell the service without permission</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Your content">
        <p>
          You retain ownership of contracts and other materials you upload. You grant
          us a limited license to store, process, and analyze that content solely to
          provide the service to you.
        </p>
        <p>
          You represent that you have the necessary rights to upload your documents
          and that doing so does not violate any confidentiality or third-party
          obligations.
        </p>
      </LegalSection>

      <LegalSection heading="AI-generated output">
        <p>
          Analysis results are generated by artificial intelligence and may contain
          errors or omissions. We do not guarantee accuracy, completeness, or
          suitability for any particular purpose. You are solely responsible for how
          you use or rely on any output.
        </p>
      </LegalSection>

      <LegalSection heading="Plans and payment">
        <p>
          Some features may require payment or credits. Prices and plan details are
          shown on our website. We may change pricing with reasonable notice. Refund
          policies, if any, will be stated at the time of purchase.
        </p>
      </LegalSection>

      <LegalSection heading="Availability">
        <p>
          We strive to keep YourFineprint available but do not guarantee uninterrupted
          access. We may modify, suspend, or discontinue features with or without
          notice.
        </p>
      </LegalSection>

      <LegalSection heading="Disclaimer of warranties">
        <p>
          YourFineprint is provided &quot;as is&quot; and &quot;as available&quot; without
          warranties of any kind, whether express or implied, including implied
          warranties of merchantability, fitness for a particular purpose, and
          non-infringement.
        </p>
      </LegalSection>

      <LegalSection heading="Limitation of liability">
        <p>
          To the fullest extent permitted by law, YourFineprint and its operators will
          not be liable for any indirect, incidental, special, consequential, or
          punitive damages, or for any loss of profits, data, or business
          opportunities arising from your use of the service. Our total liability for
          any claim related to the service is limited to the amount you paid us in
          the twelve months before the claim, or €50, whichever is greater.
        </p>
      </LegalSection>

      <LegalSection heading="Termination">
        <p>
          You may stop using YourFineprint at any time. We may suspend or terminate your
          access if you violate these Terms or if required for security or legal
          reasons.
        </p>
      </LegalSection>

      <LegalSection heading="Governing law">
        <p>
          These Terms are governed by the laws applicable in the operator&apos;s
          jurisdiction, without regard to conflict-of-law principles. Disputes will
          be resolved in the courts of that jurisdiction, unless mandatory consumer
          protection laws in your country require otherwise.
        </p>
      </LegalSection>

      <LegalSection heading="Changes">
        <p>
          We may update these Terms from time to time. Continued use of YourFineprint
          after changes take effect constitutes acceptance of the updated Terms.
        </p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>
          Questions about these Terms? Use our{' '}
          <Link href="/contact">contact form</Link>.
        </p>
      </LegalSection>
    </LegalDocument>
  );
}
